version: "3.8"
services:
  education-service:
    container_name: education-container
    image: education-image
    restart: always
    build: .
    ports:
      - "8090:8080"
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_DB_NAME: springlearn
      MYSQL_USER: root
      MYSQL_PASSWORD: 04311
      MYSQL_PORT: 3306


  mysqldb:
    container_name: mysql-container
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: springlearn
      MYSQL_ROOT_PASSWORD: 04311

volumes:
  db: